dialogStyle = "background-color: rgb(57, 162, 219)\n"""

encryptDropDownStyle = ("QComboBox{\n"
"    font: 14pt \"Segoe UI Emoji\";\n"
"    padding-left: 10px;\n"
"    background-color: #E8F0F2;\n"
"    border: 3px solid #A2DBFA;\n"
"    color: #053742;\n"
"    radius: 8px;\n"
"    border-radius: 8px;\n"
"    selection-background-color: #A2DBFA;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    color: white;\n"
"    background-color: #E8F0F2;\n"
"    border: 0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"   image: url(:/images/dropdown.png);\n"
"   width: 14px;\n"
"   height: 14px;\n"
"   padding-right: 10px;\n"
"   border: 0;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"     image: url(:/images/dropdown_on.png);\n"
"}\n"
"QListView{\n"
"  margin-top: 10px;\n"
"  color: #fff;\n"
"  border: 3px solid #A2DBFA;\n"
"  radius: 8px;\n"
"  border-radius: 8px;\n"
"  selection-color: white;\n"
"  selection-background-color: #A2DBFA;\n"
"  outline: none;\n"
"  cursor: pointer;\n"
"  \n"
"}\n""")

messagesAreaStyle = ("QTextBrowser#messagesArea\n"
"{\n"
"    font: 12pt \"Segoe UI Emoji\";\n"
"    background-color: #E8F0F2;\n"
"    radius: 12px;\n"
"    border-radius: 8px;\n"
"    border: 3px solid #A2DBFA;\n"
"    padding-left: 10px;\n"
"    color: #053742;\n"
"}\n""")

scrollBarStyle = ("QScrollBar:vertical {\n"
"        border-left: 3px solid #A2DBFA;\n"
"        background: #A2DBFA;\n"
"    }\n"
"    QScrollBar::handle:vertical {\n"
"        background: #39A2DB;\n"
"        border-radius: 20px;\n"
"    }\n"
"    QScrollBar::add-line:vertical {\n"
"        background: none;\n"
"        height: 2px;\n"
"        subcontrol-position: bottom;\n"
"        subcontrol-origin: margin;\n"
"    }\n"
"    QScrollBar::sub-line:vertical {\n"
"        background: none;\n"
"        height: 2px;\n"
"        subcontrol-position: top left;\n"
"        subcontrol-origin: margin;\n"
"        position: absolute;\n"
"    }\n"
"    QScrollBar:up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"        background: none;\n"
"    }\n"
"    QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"        background: none;\n"
"    }\n""")

messageInputStyle = ("QTextEdit{\n"
"    color: #053742;\n"
"    padding-left: 10px;\n"
"    font: 12pt \"Segoe UI Emoji\";\n"
"    border: 3px solid;\n"
"    border-color: #A2DBFA;\n"
"    border-radius: 8px;\n"
"    background: #E8F0F2;\n"
"}\n""")

sendButtonStyle = ("QPushButton\n"
"{\n"
"    font: 8pt \"Segoe UI Emoji\";\n"
"    color: #053742;\n"
"    font-size: 14px;\n"
"    background-color: #E8F0F2;\n"
"    radius: 8px;\n"
"    border-radius: 8px;\n"
"    border: 3px solid #A2DBFA;\n"
"    letter-spacing: 2px;\n"
"    outline: none; \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #A2DBFA;\n"
"    border: 3px solid #053742;\n"
"    color: #053742;\n"
"}\n""")
